### PR TITLE
Fix broken unsubscribe…

### LINKED ISSUE #597: race condition in tests on NewBlock event
Race condition in test on new block event for tendermint v0.9.2 on (develop / 0.17)

```
github.com/hyperledger/burrow/rpc/tendermint/test
=== RUN   TestSubscribe
--- FAIL: TestSubscribe (1.01s)
    websocket_client_test.go:298: Continued to see NewBlock event after unsubscribing
```

- `burrow version` 0.17.0

### PR DESCRIPTION
**Pull request by silasdavis**
Also don't rely on go-rpc's definition of `Unsubscribe` and `Subscribe`, which even when it was compatible with ours was only 'by chance' (and history). So we:

- Use 'eventId' arg name for `Subscribe` consistently
- Use 'subscriptionId' arg name for `Unsubscribe` consistently
- Centralise subscribe/unsubsribe in `rpc/tendermint/client` package (used by tests and `NodeClient`) in a similar way as the non-websocket call-based methods are.

fixes #597

### CODE REVIEW

File: rpc/tendermint/test/websocket_client_test.go [hunk 1]
```diff
@@ -260,29 +260,32 @@ func TestSubscribe(t *testing.T) {
...
-		case <-timeout.C:
+		case <-timeout:
 			t.Fatal("Timed out waiting for subscription result")
 
 		case bs := <-wsc.ResultsCh:
 			resultSubscribe, ok := readResult(t, bs).(*core_types.ResultSubscribe)
 			if ok {
 				assert.Equal(t, txs.EventStringNewBlock(), resultSubscribe.Event)
 				subId = resultSubscribe.SubscriptionId
+				fmt.Printf("\x1b[30m\x1b[46mMARMOT!: subid %s\x1b[0m\n", subId)
```
Comment (benjaminbollen) [inline rpc/tendermint/test/websocket_client_test.go]: Battle marmot needs to return to base

Comment (silasdavis) [inline rpc/tendermint/test/websocket_client_test.go]: Haha. Dammit those special ops marmots can be hell to extract from the field once they've gone to ground.
