### PR TITLE
secp256k1 cannot validate therefore should not be able to bond

### LINKED ISSUE #1352: Bonding with secp256k1 breaks consensus
It is not possible to become a validator with the secp256k1 digital signature scheme as ethereum addressing is unsupported by tendermint. We should fail early if we detect such an account tries to bond.

### PR DESCRIPTION
**Pull request by gregdhill**
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>

Fixes #1352

### CODE REVIEW

File: execution/contexts/bond_context.go [hunk 1]
```diff
@@ -33,6 +34,11 @@ func (ctx *BondContext) Execute(txe *exec.TxExecution, p payload.Payload) error
 		return err
 	}
 
+	ct := account.PublicKey.GetCurveType()
+	if ct == crypto.CurveTypeSecp256k1 {
```
Comment (silasdavis) [inline execution/contexts/bond_context.go]:
```suggestion
	if ct != crypto.CurveTypeEd25519 {
```
Probably preferred... then again, if tendermint did add, say BLS then it probably would be supported
